### ISSUE TITLE
Running driver on V2.70-large

### ISSUE THREAD

**Issue by magpern** [Tobi177/venus-chargerybms#6]
I am trying to run the driver on V2.70-4-large-16
It won't start. Tried to start it manually too. I get this. Any idea?

root@einstein:/opt/victronenergy/chargerybms# python chargerybms.py -d /dev/ttyCHGBMS01 --victron

Traceback (most recent call last):
  File "chargerybms.py", line 69, in <module>
    dbusservice = VeDbusService(driver['connection'])
  File "./ext/velib_python/vedbus.py", line 75, in __init__
    self._dbusname = dbus.service.BusName(servicename, self._dbusconn, do_not_queue=True)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 144, in __new__
    raise NameExistsException(name)
dbus.exceptions.NameExistsException: Bus name already exists: com.victronenergy.battery.ttyCHGBMS01
Exception AttributeError: "'VeDbusService' object has no attribute '_dbusname'" in <bound method VeDbusService.__del__ of <vedbus.VeDbusService object at 0xb6401390>> ignored

**Comment by magpern** [comment]
@Tobi177 please help!

If running of 2.65 it works fine. Just installing 2.70 it stops to work. Reverting back to 2.65 it starts to work again

**Comment by magpern** [comment]
No interest in thes from the community I assume.

I fixed it in my branch. My branch is the same code as this branch, but with the extra feature that it is a real battery soc monitor for victron.

If interested:
Something has changed with the SPECIAL_DISPLAY_SYMBOLS['degree'] in the venusos-large
it says it cannot display it.
I removed it.

https://github.com/magpern/venus-chargerybms
